# This workflow will publish a release

name: publish-release

on:
  push:
    tags:
      - 'v*'

jobs:

  ci:
    name: CI
    uses: ./.github/workflows/ci.yml

  build-multiarch:
    name: Build binaries
    needs: ci
    uses: ./.github/workflows/build-multiarch.yml

  create-update-github-release:
    name: Create or Update GitHub Release
    needs: build-multiarch
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: netwait
          path: build

      - name: Check Release
        id: check-release
        run: |
          if gh release view $GITHUB_REF_NAME; then
            echo "Release already created for tag"
            releaseExists='true'
          else
            echo "Release for tag $GITHUB_REF_NAME does not exist"
            releaseExists='false'
          fi
          echo "release-exists=$releaseExists" >> $GITHUB_OUTPUT

      - name: Create Release
        if: steps.check-release.outputs.release-exists != 'true'
        run: gh release create $GITHUB_REF --generate-notes build/* 

      - name: Upload to Release
        if: steps.check-release.outputs.release-exists == 'true'
        run: gh release upload $GITHUB_REF_NAME build/* --clobber

  publish-docker:
    name: Publish Docker image
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Docker Metadata action
        id: meta
        uses: docker/metadata-action@v4.1.1
        with:
          images: gwre/netwait
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker images
        uses: docker/build-push-action@v3.2.0
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            version=${{ steps.meta.outputs.version }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
